### ISSUE TITLE
make a release?

### ISSUE THREAD

**Issue by dimpase** [freetdi/tdlib#34]
Sagemath ships a very old tdlib, which we'd really like to update (basically, we only would use the C++ headers part).
It would be of course much easier for us if there was a release made.

**Comment by dimpase** [comment]
@dcoudert

**Comment by llarisch** [comment]
tdlib already has a cython interface - see /tdlib/cytdlib.pyd to pick algorithms that may be of interest. The  cython clue code can be copied or used.. Please forward to sage trac.

It was not possible to include tdlib through its headers only because the native sage boost graph was of incompatible type. 

I'll find out whether current sage+tdlib still work..

**Comment by felix-salfelder** [comment]
On Fri, Oct 23, 2020 at 03:22:17AM -0700, Dima Pasechnik wrote:
> Sagemath ships a very old tdlib, which we'd really like to update (basically, we only would use the C++ headers part).
> It would be of course much easier for us if there was a release made.

I made a release a year ago [1]. This includes the rename to treedec and
the python3 fixes.

(I could not find the time to get rid of github, and I am not as convinced
of gitlab as it may seem).

thanks
felix

[1] https://gitlab.com/freetdi/treedec/-/releases

**Comment by dimpase** [comment]
Thanks, so is gitlab the preferred upstream?
I would still keep a mirror of your repo on github, just in case.

By the way, you can comment on  Sage trac and commit to Sage's git using your github accounts.

**Comment by felix-salfelder** [comment]
bugfix release. https://gitlab.com/freetdi/treedec/-/tags/v0.9.1
