### ISSUE TITLE
Macro names

### ISSUE THREAD

**Issue by spth** [freetdi/tdlib#9]
tdlib exposes some macros. To reduce the risk of name conflicts, these should be renamed to have a common tdlib-specific prefix.

Currently, some macros have no prefix at all. Some have prefix TD_. Some have prefix  TDLIB_. One could also choose a different prefix.

I can make the required changes, but I need to know which prefix I should use. Personally, I'd prefer TDLIB_ (TD_ seems a bit short, and thus more likely to leave potential name conflicts).

Philipp

**Comment by felix-salfelder** [comment]
thanks, this looks good.

there is some historic preprocessor macro abuse going on between gala and tdlib. something with bundled properties. will try to come up with a workaround, then merge.

(the resaon why this "succeds" with clang++, is that this part is disabled for clang, because -fprofile strangely different in clang++...)

**Comment by felix-salfelder** [comment]
this is fixed with your PR #12
